### ISSUE TITLE
Trouble in custom icon

### ISSUE THREAD

**Issue by RastaDill** [audoban/dolphin-folder-color#5]
Use Dolphin version 4.14.13 (KDE4).
When i selects Custom icon the nothing happens.
If run ./dolphin-folder-color.sh -c the selection window icons opens

Please fix this bug

**Comment by audoban** [comment]
At the night I will fix. Thanks for your reporting.

**Comment by audoban** [comment]
xD Fixed. Please try the version master
https://github.com/audoban/dolphin-folder-color/commit/27dd40b16d5ba0e5d255f1c57c19ca67b3a9332a

**Comment by RastaDill** [comment]
Thank you. Now it works! :-)
