### ISSUE TITLE
Color change behaviour

### ISSUE THREAD

**Issue by brezn1** [audoban/dolphin-folder-color#7]
Changing folder color seems to strip off the symbols. Is this the intended behaviour?

![screenshot_1250](https://cloud.githubusercontent.com/assets/5721488/22650138/1d95442e-ec7e-11e6-977c-eddee2128dee.png)
![screenshot_1251](https://cloud.githubusercontent.com/assets/5721488/22650145/289a21d2-ec7e-11e6-88a3-59e10b8b7649.png)

KDE 5.9 Breeze Theme

**Comment by audoban** [comment]
I can't avoid this. dolphin-foder-color change the icon, Is not able to color folders with symbols.

**Comment by brezn1** [comment]
Thanks for clarification. Just wasn't sure if its a feature or a bug on my system ;-)

**Comment by audoban** [comment]
Hello again,
